//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Janus.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Janus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying: {0}.
        /// </summary>
        internal static string Auto_Copying_Target {
            get {
                return ResourceManager.GetString("Auto_Copying_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting: {0}.
        /// </summary>
        internal static string Auto_Deleting_Target {
            get {
                return ResourceManager.GetString("Auto_Deleting_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking for copy: {0}.
        /// </summary>
        internal static string Auto_Mark_Copy_Target {
            get {
                return ResourceManager.GetString("Auto_Mark_Copy_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking for delete: {0}.
        /// </summary>
        internal static string Auto_Mark_Delete_Target {
            get {
                return ResourceManager.GetString("Auto_Mark_Delete_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from delete list? {0}.
        /// </summary>
        internal static string Auto_Remove_Delete_List {
            get {
                return ResourceManager.GetString("Auto_Remove_Delete_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing from delete list: {0}.
        /// </summary>
        internal static string Auto_Remove_Delete_Target {
            get {
                return ResourceManager.GetString("Auto_Remove_Delete_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from copy list? {0}.
        /// </summary>
        internal static string Auto_Removed_Target {
            get {
                return ResourceManager.GetString("Auto_Removed_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing from copy list: {0}.
        /// </summary>
        internal static string Auto_Removing_Target {
            get {
                return ResourceManager.GetString("Auto_Removing_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while copying file {1}:
        ///	.
        /// </summary>
        internal static string Copy_Error {
            get {
                return ResourceManager.GetString("Copy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new watcher..
        /// </summary>
        internal static string Debug_Added_Watcher {
            get {
                return ResourceManager.GetString("Debug_Added_Watcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path!.
        /// </summary>
        internal static string Debug_Invalid_Path {
            get {
                return ResourceManager.GetString("Debug_Invalid_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while deleting file {1}:
        ///	.
        /// </summary>
        internal static string Delete_Error {
            get {
                return ResourceManager.GetString("Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DataStore file found: &apos;{0}&apos;; removing file..
        /// </summary>
        internal static string Invalid_DataStore {
            get {
                return ResourceManager.GetString("Invalid_DataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Manual] Copying: {0}.
        /// </summary>
        internal static string Manual_Copying_Target {
            get {
                return ResourceManager.GetString("Manual_Copying_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Manual] Deleting: {0}.
        /// </summary>
        internal static string Manual_Deleting_Target {
            get {
                return ResourceManager.GetString("Manual_Deleting_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while copying file {1}:
        ///	.
        /// </summary>
        internal static string Sync_Add_ {
            get {
                return ResourceManager.GetString("Sync_Add_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while deleting file {1}:
        ///	.
        /// </summary>
        internal static string Sync_Delete_ {
            get {
                return ResourceManager.GetString("Sync_Delete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping watcher for &apos;{0}&apos;.
        /// </summary>
        internal static string Watcher_Stop_Target {
            get {
                return ResourceManager.GetString("Watcher_Stop_Target", resourceCulture);
            }
        }
    }
}
