//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Janus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied: {0}.
        /// </summary>
        internal static string Auto_Copied_Target {
            get {
                return ResourceManager.GetString("Auto_Copied_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying: {0}.
        /// </summary>
        internal static string Auto_Copying_Target {
            get {
                return ResourceManager.GetString("Auto_Copying_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted: {0}.
        /// </summary>
        internal static string Auto_Deleted_Target {
            get {
                return ResourceManager.GetString("Auto_Deleted_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting: {0}.
        /// </summary>
        internal static string Auto_Deleting_Target {
            get {
                return ResourceManager.GetString("Auto_Deleting_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking for copy: {0}.
        /// </summary>
        internal static string Auto_Mark_Copy_Target {
            get {
                return ResourceManager.GetString("Auto_Mark_Copy_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking for delete: {0}.
        /// </summary>
        internal static string Auto_Mark_Delete_Target {
            get {
                return ResourceManager.GetString("Auto_Mark_Delete_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from delete list? {0}.
        /// </summary>
        internal static string Auto_Remove_Delete_List {
            get {
                return ResourceManager.GetString("Auto_Remove_Delete_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing from delete list: {0}.
        /// </summary>
        internal static string Auto_Remove_Delete_Target {
            get {
                return ResourceManager.GetString("Auto_Remove_Delete_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from copy list? {0}.
        /// </summary>
        internal static string Auto_Removed_Target {
            get {
                return ResourceManager.GetString("Auto_Removed_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing from copy list: {0}.
        /// </summary>
        internal static string Auto_Removing_Target {
            get {
                return ResourceManager.GetString("Auto_Removing_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while copying file {1}:
        ///	.
        /// </summary>
        internal static string Copy_Error {
            get {
                return ResourceManager.GetString("Copy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new watcher..
        /// </summary>
        internal static string Debug_Added_Watcher {
            get {
                return ResourceManager.GetString("Debug_Added_Watcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path!.
        /// </summary>
        internal static string Debug_Invalid_Path {
            get {
                return ResourceManager.GetString("Debug_Invalid_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while deleting file {1}:
        ///	.
        /// </summary>
        internal static string Delete_Error {
            get {
                return ResourceManager.GetString("Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DataStore file found: &apos;{0}&apos;; removing file..
        /// </summary>
        internal static string Invalid_DataStore {
            get {
                return ResourceManager.GetString("Invalid_DataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Manual] Copying: {0}.
        /// </summary>
        internal static string Manual_Copying_Target {
            get {
                return ResourceManager.GetString("Manual_Copying_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Manual] Deleting: {0}.
        /// </summary>
        internal static string Manual_Deleting_Target {
            get {
                return ResourceManager.GetString("Manual_Deleting_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking file to be renamed: {0}.
        /// </summary>
        internal static string Mark_File_Rename {
            get {
                return ResourceManager.GetString("Mark_File_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0} to {1}.
        /// </summary>
        internal static string Renaming_File_From_To {
            get {
                return ResourceManager.GetString("Renaming_File_From_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while copying file {1}:
        ///	.
        /// </summary>
        internal static string Sync_Add_ {
            get {
                return ResourceManager.GetString("Sync_Add_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while deleting file {1}:
        ///	.
        /// </summary>
        internal static string Sync_Delete_ {
            get {
                return ResourceManager.GetString("Sync_Delete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping watcher for &apos;{0}&apos;.
        /// </summary>
        internal static string Watcher_Stop_Target {
            get {
                return ResourceManager.GetString("Watcher_Stop_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type already registered. Currently only one handler per message is supported..
        /// </summary>
        internal static string WndProcBus_Error_AlreadyRegisted {
            get {
                return ResourceManager.GetString("WndProcBus_Error_AlreadyRegisted", resourceCulture);
            }
        }
    }
}
